"""
Django settings for caltable project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1ww#6jph6an(s0xcf2)c8235a14iw6vuuhexi31v!e^db%#dx9"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
# AUTHENTICATION_BACKENDS = ("mozilla_django_oidc.auth.OIDCAuthenticationBackend",)
LOGIN_URL = '/admin/login/'
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    'mozilla_django_oidc',
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "caltable.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "caltable.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

OIDC_USE_PKCE = True
OIDC_PKCE_CODE_CHALLENGE_METHOD = 'S256'
OIDC_PKCE_CODE_VERIFIER_SIZE = 128
OIDC_RP_CLIENT_ID='26wMRNQ3oyvwiqFLc7YgvgLEANkAixp2eOObpBe9'
OIDC_RP_CLIENT_SECRET='xoBTT9OiRbw9MUYNyaDNLzgGV8illTSc3SZZi1cK8nS7aOAUvsad7LxvaNXue5V1VUmMlor0fzvxsNf985bgh6jYnjFVkaFQEW5Y4eFVNh9FEXtahtMZWRe8ujwOEP8H'
ISSUER='https://jellyroll.cs.tulane.edu/jauth/o'

OIDC_OP_AUTHORIZATION_ENDPOINT = ISSUER + "/authorize/"
OIDC_OP_TOKEN_ENDPOINT = ISSUER + "/token/"
OIDC_OP_USER_ENDPOINT = ISSUER + "/userinfo/"
OIDC_OP_JWKS_ENDPOINT = ISSUER + "/.well-known/jwks.json"
OIDC_RP_SCOPES = "openid email"
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_CREATE_USER = False
OIDC_VERIFY_SSL = False
LOGIN_REDIRECT_URL = "http://127.0.0.1:8000"
LOGOUT_REDIRECT_URL = ISSUER + "/logout?client_id=" + OIDC_RP_CLIENT_ID

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 36000